### ISSUE TITLE
Option to dispaly the note only on the specific URL where it was created

### ISSUE THREAD

**Issue by smartfonreddit** [wildskyf/pageMemo#9]
Thanks for the great addon!

Currently, creating a note on _www.website.com/video1/_ page will also display the note on _www.website.com/video2/_

An option to display it only on the page where it was created would make it a lot more useful.

**Comment by wildskyf** [comment]
Hi @smartfonreddit ,

I decide to change the identify rule from 'hostname + pathname' to 'href'
which means notes will appear only when the url are 100% matched.

You might think it is too strict, but you could browse all your saved notes since v1.6.0.
And you could go to the url you saved memo via easily click on item in list.
So that the rule is stricter might be good I think.

Thanks for your suggestion. Feel free to rise any other feature. :)
